services:
  postgres:
    image: postgres:15
    container_name: thekingside-postgres
    environment:
      POSTGRES_DB: thekingside
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: thekingside-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data_v2:
  redis_data:
